# Generated by Django 4.0.4 on 2022-05-20 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('state', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('cVitae', models.FileField(blank=True, null=True, upload_to='cVitae/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['id'],
            },
        ),
    ]
